### ISSUE TITLE
Luarocks please

### ISSUE THREAD

**Issue by pisto** [daurnimator/mmdblua#1]
Care to make a luarocks release?

**Comment by daurnimator** [comment]
Run: `luarocks install --server=http://rocks.moonscript.org/manifests/daurnimator mmdblua`

I don't feel the library is ready for a proper release yet; needs more work (which sadly I don't have time for); so I've only published it as a scm rock.

**Comment by pisto** [comment]
It is however of much better quality than the only geoip module there as of now, even only for the fact thta this uses the new database format.

**Comment by daurnimator** [comment]
> It is however of much better quality than the only geoip module there as of now, even only for the fact thta this uses the new database format.
> Thanks :)

If you're interested on working on it, see if you can fix #3.
