### ISSUE TITLE
maxmind GeoIP2-Anonymous-database not working

### ISSUE THREAD

**Issue by Prasanna-sr** [daurnimator/mmdblua#12]
I tried the module on GeoIP2-Anonymous-database from maxmind (tried couple of latest versions)

i got assert error, "wrong key type" on the line below. 
https://github.com/daurnimator/mmdblua/blob/master/mmdb/init.lua#L258

**Comment by daurnimator** [comment]
Do maxmind have the database available for debugging somewhere? (or a sample in the same format?)
I need to be able to replicate to help you debug.

Otherwise, could you let me know what the type of `key` is instead?
And/or the full traceback?

**Comment by oschwald** [comment]
There is a test database in [the MaxMind-DB repo](https://github.com/maxmind/MaxMind-DB/tree/master/test-data). All the values in this database are booleans.

**Comment by Prasanna-sr** [comment]
I think all keys are strings and values are boolean. Are you able to
replicate the issue with test DB ?

**Comment by daurnimator** [comment]
Should be fixed with c1b1a20e7f530cde633b8845acd039ed15a60789

**Comment by Prasanna-sr** [comment]
thanks. could you please publish this version in luarocks
