### ISSUE TITLE
Provide a release tarball

### ISSUE THREAD

**Issue by fcambus** [daurnimator/mmdblua#14]
It would be nice if you would consider adding proper source release tarballs,
as GitHub auto-generated tarballs are not immutable. This is an issue [1] for
operating systems creating packages for mmdblua. Thanks in advance.

[1] https://marc.info/?l=openbsd-ports&m=151973450514279&w=2

**Comment by daurnimator** [comment]
Ah; I didn't know that auto-generated tarballs are not immutable :(

However, I *have* uploaded .rock files to the v0.1 release. https://github.com/daurnimator/mmdblua/releases/tag/v0.1

Are you installing via some non-luarocks mechanism?

**Comment by fcambus** [comment]
Yes, we don't have luarocks on OpenBSD, so we have ports for Lua modules. Packages are built from source tarballs, and checksums are performed on the tarballs, which is causing issues with GitHub auto-generated tarballs.

**Comment by daurnimator** [comment]
Have you considered using the .src.rock file?

**Comment by fcambus** [comment]
I suppose it would be possible to use this as a fallback solution, but having a tarball would be easier than dealing with nested ZIP files :)

**Comment by daurnimator** [comment]
Ah I didn't realise it was nested.

FWIW, luarocks was the only supported compilation/installation for most of my lua projects; so providing a .src.rock file as the "source tarball" seemed like the simplest solution.
However this one is a simple project where there is no compile step; and installation is simply copying files to the correct location... which makes it tempting for maintainers to skip using luarocks.

Hrm. trying to think of the best way to integrate things into my release process.

**Comment by daurnimator** [comment]
FWIW I just tagged a v0.2 release.
How do you suggest I create the release tarball for you?

Is `git archive` enough? note that some tests require a git submodule.

**Comment by fcambus** [comment]
I assume `git archive` is what's used to produce the auto-generated tarballs such as the one generated by triggering this URL? https://github.com/daurnimator/mmdblua/archive/v0.2.tar.gz

If so, that would be perfect, yes. You can simply upload mmdblua-0.2.tar.gz as a release asset. Thanks!

**Comment by daurnimator** [comment]
The git archive format is now stable (see discussion at https://www.mail-archive.com/aur-general@archlinux.org/msg33169.html), so this is not required.
