### ISSUE TITLE
Do not use ABI to detect number endian in then database

### ISSUE THREAD

**Issue by moteus** [daurnimator/mmdblua#15]
I have system where I have `ffi.abi('le')` false, but mmdb file has such endian.
So as result I have wrong value in record_size.
I suggest detect endian based on e.g. IP version format. It can be either 6 or 4.

**Comment by daurnimator** [comment]
Did anything need to be done here?

**Comment by moteus** [comment]
No. It was as broken ffi implementation which always return false on ffi.abi.
I just change condition from `ffi.abi('le')` to `not ffi.abi('be')` :)
