### ISSUE TITLE
can i integrate your module without luarocks?

### ISSUE THREAD

**Issue by hacker0000** [daurnimator/mmdblua#16]
hi buddy, you wrote a very nice useful module, thank!
but is there any way that i can integrate your module without luarocks?

**Comment by daurnimator** [comment]
@hacker0000 what do you mean by 'integrate'?
e.g. 
  - Do you want to install it on a linux PC? (which distro?)
  - Do you want to include it with your own program?

**Comment by hacker0000** [comment]
@daurnimator thanks for reply~ sorry for my words
i mean like ... require into my lua script but without luarocks (your 2rd e.g. i think)

**Comment by daurnimator** [comment]
You could do it by copying the `mmdb` directory into anywhere in your lua search path.
If you are distributing it, make sure you ship the LICENSE file too!

**Comment by hacker0000** [comment]
thanks! i will try it, very thank you ~
best wish!
