### ISSUE TITLE
Use new 5.3 string.unpack instead of home grown reading.

### ISSUE THREAD

**Issue by daurnimator** [daurnimator/mmdblua#3]
At the moment we use some hacky routines to read/write doubles: https://github.com/daurnimator/mmdblua/blob/f0644b7478ec91fd8a7d85a9f0f259f444ba20cd/IEEE-754.lua
As well as some simple routines to read ints: https://github.com/daurnimator/mmdblua/blob/f0644b7478ec91fd8a7d85a9f0f259f444ba20cd/mmdb.lua#L179

Lua 5.3 brings with it new function [`string.unpack`](http://www.lua.org/manual/5.3/manual.html#pdf-string.unpack) which can be used to tidy this up.
[compat-5.3](https://github.com/keplerproject/lua-compat-5.3) can be used to bring this functionality to lua 5.1 and 5.2. Preferably we stay compatible with [Roberto's struct library](http://www.inf.puc-rio.br/~roberto/struct/) too.

**Comment by pisto** [comment]
I'm looking into this. Should I ditch the current implementation and require either 5.3, either compat-5.3, either Robert's structs? Afterall, you already require bitops.

**Comment by daurnimator** [comment]
> Should I ditch the current implementation and require either 5.3, either compat-5.3, either Robert's structs? Afterall, you already require bitops.

Yes. It's fine to depend on 5.3, compat53 or struct.

**Comment by daurnimator** [comment]
Implemented in 8d27daaa69bbe86070ea949d50639e5930d2f81f
